export const menu = [
  {
    name: "Home",
    path: "/",
  },
  {
    name: "Pregnancy",
    submenu: [
      { name: "Pregnancy Week by Week", path: "/about/team" },
      { name: "First Trimester", path: "/about/mission" },
      { name: "Second Trimester", path: "/about/mission" },
      { name: "Third Trimester", path: "/about/mission" },
      { name: "Health & Wellness", path: "/about/mission" },
      { name: "Morning Sickness", path: "/about/mission" },
      { name: "Pregnancy Symptoms", path: "/about/mission" },
      { name: "Life & Career", path: "/about/mission" },
      { name: "Twins & Multiples", path: "/about/mission" },
      { name: "Baby Showers & Reveals", path: "/about/mission" },
      { name: "Labor & Delivery", path: "/about/mission" },
      { name: "Miscarriage & Pregnancy Loss", path: "/about/mission" },
    ],
  },
  {
    name: "Baby & Toddler",
    submenu: [
      { name: "Newborn", path: "/services/car-repair" },
      { name: "Baby Month by Month", path: "/services/car-repair" },
      { name: "Baby's Firsts", path: "/services/car-repair" },
      { name: "Breastfeeding", path: "/services/car-repair" },
      { name: "Bottle Feeding", path: "/services/car-repair" },
      { name: "Feeding", path: "/services/car-repair" },
      { name: "Sleep", path: "/services/car-repair" },
      { name: "Baby Health & Wellness", path: "/services/car-repair" },
      { name: "Childcare", path: "/services/car-repair" },
      { name: "Twins & Multiples", path: "/services/car-repair" },
      { name: "Toddler Month by Month", path: "/services/car-repair" },
    ],
  },
  {
    name: "Baby & Toddler",
    submenu: [
      { name: "Newborn", path: "/services/car-repair" },
      { name: "Newborn", path: "/services/car-repair" },
      { name: "Newborn", path: "/services/car-repair" },
      { name: "Newborn", path: "/services/car-repair" },
      { name: "Newborn", path: "/services/car-repair" },
      { name: "Newborn", path: "/services/car-repair" },
      { name: "Newborn", path: "/services/car-repair" },
      { name: "Newborn", path: "/services/car-repair" },
      { name: "Newborn", path: "/services/car-repair" },
    ],
  },
  {
    name: "Contact",
    path: "/contact",
  },
];